# Generated by Django 3.2.7 on 2021-09-28 18:32

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeUrgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('identifier', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Identifier')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Type urgency',
                'verbose_name_plural': 'Type urgencies',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('quantity', models.CharField(max_length=128, verbose_name='Quantity')),
                ('bought', models.BooleanField(verbose_name='Bought')),
                ('urgency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping.typeurgency', verbose_name='Urgency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
