# Generated by Django 3.2.7 on 2021-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='bought',
            field=models.BooleanField(default=False, verbose_name='Bought'),
        ),
    ]
