# Generated by Django 3.2.7 on 2021-10-02 08:18

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shoppingitem_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('user', models.CharField(max_length=128, verbose_name='User')),
                ('money_amount', models.IntegerField(verbose_name='Money amount')),
                ('paid_back', models.BooleanField(default=False, verbose_name='Paid back')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
