# Generated by Django 3.2.7 on 2021-09-19 15:24

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepoverRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('requester_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Requester name')),
                ('sleepover_date_from', models.DateField(blank=True, null=True, verbose_name='Sleepover date from')),
                ('sleepover_date_to', models.DateField(blank=True, null=True, verbose_name='Sleepover date to')),
                ('num_persons', models.CharField(blank=True, max_length=4, null=True, verbose_name='Number of persons')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('coitus', models.BooleanField(default=False, verbose_name='Is coitus')),
                ('estimated_coitus_time_start', models.TimeField(blank=True, null=True, verbose_name='Estimated coitus time start')),
                ('estimated_coitus_time_end', models.TimeField(blank=True, null=True, verbose_name='Estimated coitus time start')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
