# Generated by Django 3.2.7 on 2021-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepover_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepoverrequest',
            name='estimated_arrive_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Estimated arrive time'),
        ),
        migrations.AddField(
            model_name='sleepoverrequest',
            name='estimated_leave_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Estimated leave time'),
        ),
    ]
