# Generated by Django 3.2.7 on 2021-09-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleepover_form', '0003_auto_20210925_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecoitusprobability',
            options={'ordering': ['-order'], 'verbose_name': 'Type coitus probability', 'verbose_name_plural': 'Type coitus probabilities'},
        ),
    ]
