# Generated by Django 3.2.7 on 2021-09-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepover_form', '0005_sleepoverrequest_coitus_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecoitusprobability',
            name='description_alt',
            field=models.CharField(default='', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
