# Generated by Django 3.2.7 on 2021-09-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleepover_form', '0008_shoppinglist_typeurgency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='ShoppingItem',
        ),
    ]
